modLoader = "javafml"
loaderVersion = "*"
license = "Polyform-Shield-1.0"

[[mods]]
modId = "sodium"

version = "${version}"
displayName = "Sodium"

logoFile="sodium-icon.png" #optional

authors="JellySquid"

description = '''
Sodium is a powerful rendering engine for Minecraft which improves frame rates and reduces lag spikes.
'''

[[dependencies.sodium]]
modId = "embeddium"
mandatory = false
versionRange = "[,0.0.1-INCOMPATIBLE-WITH-SODIUM)"
ordering = "NONE"
side = "CLIENT"

provides = ["indium"]

[modproperties.sodium]
"fabric-renderer-api-v1:contains_renderer"=true