modLoader = "javafml"
loaderVersion = "*"
license = "Polyform-Shield-1.0"

[[mods]]
modId = "sodium"

version = "${version}"
displayName = "Sodium"

logoFile="sodium-icon.png" #optional

authors="JellySquid"

description = '''
Sodium is a powerful rendering engine for Minecraft which improves frame rates and reduces lag spikes.
'''

provides = ["indium"]

[modproperties.sodium]
"fabric-renderer-api-v1:contains_renderer"=true

[[dependencies.sodium]]
modId="minecraft"
type="required"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="CLIENT"

[[mixins]]
config = "sodium.mixins.json"

[[mixins]]
config = "sodium-forge.mixins.json"